#!/usr/bin/env bash
# A bash script that Nginx server to have a
sudo apt-get update
sudo apt-get install -y nginx
echo "<html>
<head>
    <title>Document</title>
</head>
<body>
    <p>Hello World!</p>
</body>
</html>" > /var/www/html/index.html
