#!/usr/bin/env bash
# HAproxy, the load balancer

# HAproxy installation
apt-get update
apt-get -y install haproxy

# Configure to use roundrubin algorithm
echo '
frontend edisonasare.tech
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 66813-web-01 18.210.10.43:80
        server 66813-web-02 18.209.223.134:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy with service
service haproxy restart

